{% set name = "gprof2dot" %}
{% set version = "2022.7.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45b4d298bd36608fccf9511c3fd88a773f7a1abc04d6cd39445b11ba43133ec5

build:
  number: 0
  entry_points:
    - gprof2dot=gprof2dot:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - gprof2dot --help

about:
  home: https://github.com/jrfonseca/gprof2dot
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Generate a dot graph from the output of several profilers.

extra:
  recipe-maintainers:
    - pmgrafe
