{% set name = "gprof2dot" %}
{% set version = "2024.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gprof2dot-{{ version }}.tar.gz
  sha256: fa1420c60025a9eb7734f65225b4da02a10fc6dd741b37fa129bc6b41951e5ab

build:
  entry_points:
    - gprof2dot = gprof2dot:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - gprof2dot
  commands:
    - pip check
    - gprof2dot --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jrfonseca/gprof2dot
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Generate a dot graph from the output of several profilers.

extra:
  recipe-maintainers:
    - rxm7706
    - pmgrafe
